version: "3.7"
services:
  streaming-web:
    build:
      context: ./servers
      dockerfile: ./servers/Dockerfile
    image: bigdata-project-tornado:latest
    ports:
      - "80:10080"
    networks:
      - web_rabbitmq
  rabbitmq1:
    image: rabbitmq:3.7-management
    networks:
      - web_rabbitmq
    ports:
      - "15672:15672"
    expose:
      - "4369"
      - "5672"
      - "25672"
    hostname: rabbitmq1
    env_file:
      - ./rabbitmq/.env
    volumes:
      - rabbitmq_data_1:/var/lib/rabbitmq
      - ./rabbitmq/rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf
      - ./rabbitmq/definitions.json:/etc/rabbitmq/definitions.json
  rabbitmq2:
    image: rabbitmq:3.7-management
    depends_on:
      - rabbitmq1
    networks:
      - web_rabbitmq
    expose:
      - "5672"
    hostname: rabbitmq2
    env_file:
      - ./rabbitmq/.env
    volumes:
      - rabbitmq_data_2:/var/lib/rabbitmq
      - ./rabbitmq/rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf
      - ./rabbitmq/definitions.json:/etc/rabbitmq/definitions.json
  rabbitmq3:
    image: rabbitmq:3.7-management
    depends_on:
      - rabbitmq1
    networks:
      - web_rabbitmq
    expose:
      - "5672"
    hostname: rabbitmq3
    env_file:
      - ./rabbitmq/.env
    volumes:
      - rabbitmq_data_3:/var/lib/rabbitmq
      - ./rabbitmq/rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf
      - ./rabbitmq/definitions.json:/etc/rabbitmq/definitions.json

networks:
  web_rabbitmq:
    driver: bridge
    name: project-web-rabbitmq

volumes:
  rabbitmq_data_1:
    name: project-rabbitmq-data-1
  rabbitmq_data_2:
    name: project-rabbitmq-data-2
  rabbitmq_data_3:
    name: project-rabbitmq-data-3