version: "2.4"
services:
  streaming-web:
    build:
      context: .
      dockerfile: ./docker/Dockerfile-server
    image: bigdata-project-tornado:latest
    ports:
      - "80:10080"
    networks:
      - web_rabbitmq

  rabbitmq1:
    build:
      context: .
      dockerfile: ./docker/Dockerfile-rabbitmq
    image: bigdata-project-mq:latest
    networks:
      - web_rabbitmq
      - backend_rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    expose:
      - "4369"
      - "5672"
      - "25672"
    hostname: rabbitmq1
    env_file:
      - ./rabbitmq/.env
    volumes:
      - rabbitmq_data_1:/var/lib/rabbitmq
      - ./rabbitmq/rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf
      - ./rabbitmq/definitions.json:/etc/rabbitmq/definitions.json # this makes some things easier, some things harder
      # would not do it in a production setting, but here it is just to ease things up
    healthcheck:
      test: ["CMD", "./tmp/wait-for-it.sh", "localhost:5672", "-t", "10"]
      interval: 30s
      retries: 3
      start_period: 45s
    restart: on-failure
    mem_limit: 150M

  rabbitmq2:
    image: bigdata-project-mq:latest
    # image: rabbitmq:3.7-management
    depends_on:
      rabbitmq1:
        # condition: service_healthy
        condition: service_started
    networks:
      - web_rabbitmq
      - backend_rabbitmq
    expose:
      - "5672"
    hostname: rabbitmq2
    env_file:
      - ./rabbitmq/.env
    volumes:
      - rabbitmq_data_2:/var/lib/rabbitmq
      - ./rabbitmq/rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf
      - ./rabbitmq/definitions.json:/etc/rabbitmq/definitions.json
    healthcheck:
      test: ["CMD", "./tmp/wait-for-it.sh", "localhost:5672", "-t", "10"]
      interval: 30s
      retries: 1
      start_period: 45s
    restart: on-failure
    mem_limit: 150M

  streamer:
    build:
      context: .
      dockerfile: ./docker/Dockerfile-streaming
    image: streaming-worker:latest
    networks:
      - backend_rabbitmq
    depends_on:
      rabbitmq1:
        condition: service_healthy
      rabbitmq2:
        condition: service_healthy
    cpus: 2.5
    scale: 2

networks:
  web_rabbitmq:
    driver: bridge
    name: bigdata-project-web-rabbitmq
  backend_rabbitmq:
    driver: bridge
    name: bigdata-project-backend-rabbitmq

volumes:
  rabbitmq_data_1:
    name: bigdata-project-rabbitmq-data-1
  rabbitmq_data_2:
    name: bigdata-project-rabbitmq-data-2
  rabbitmq_data_3:
    name: bigdata-project-rabbitmq-data-3